version: "3"
services:

  db:
    image: mongo:3.6.19-xenial
    ports:
      - 27017:27017
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mern-network
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - mern-network
    volumes:
      - ./server:/usr/app/
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb+srv://test:test@cluster0.l0r7v.mongodb.net/shop?retryWrites=true&w=majority
      - CLIENT=http://localhost:3000
    command: /usr/app/node_modules/.bin/nodemon -L index.js
  
networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local